apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong # This is the app as declared in the deployment.
  ports:
    - port: 2453 # This is a port that is available to the cluster, in this case it can be ~ anything
      protocol: TCP
      targetPort: 5001 # This is the target port