apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-hash
          persistentVolumeClaim:
            claimName: hash-claim
      containers:
        - name: hashgenerator
          image: hash-generator-go:3.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-hash
            mountPath: /usr/src/app/files
          env:
            - name: HASH_FILE_PATH
              value: "/usr/src/app/files/hashes.log"