apiVersion: batch/v1
kind: Job
metadata:
  name: todo-db-init
spec:
  template:
    spec:
      containers:
        - name: psql
          env:
            - name: PGHOST
              value: prod-postgres-svc