apiVersion: batch/v1
kind: Job
metadata:
  name: todo-db-init
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: postgres:18-alpine
          env:
            - name: PGHOST
              value: prod-postgres-svc