apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-todo-generator
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wiki-todo-job
              image: random-todo:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: TODO_API_URL
                  value: "http://todo-backend-svc:2245/todos"
          restartPolicy: Never
